version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /

    schedule:
      interval: monthly

    versioning-strategy: increase

    allow:
      # Include direct package.json updates
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /

    schedule:
      interval: 'monthly'
