name: Pull request

on: pull_request

jobs:
  sonar:
    name: Sonar analysis
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    steps:
      - name: Checkout
        if: ${{ env.SONAR_TOKEN }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sonar analysis
        if: ${{ env.SONAR_TOKEN }}
        uses: SonarSource/sonarqube-scan-action@v5

  linting:
    name: Code style checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

  tests:
    name: Javascript unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test --ignore-scripts

  ui_tests:
    name: Visual regression tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run backstop
        run: npm run test:visual

      - name: Save backstop report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: Backstop report
          path: tests/backstop/
          if-no-files-found: ignore
