name: Pull request

on: pull_request

jobs:
  build:
    name: Pull request
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: npm install
  
    - task: SonarCloudPrepare@1
      displayName: 'Prepare analysis on SonarCloud'
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'nhsdigital'
        scannerMode: 'CLI'
        extraProperties: |
          sonar.projectKey=nhsuk-frontend
          sonar.exclusions=$(System.DefaultWorkingDirectory)/dependency-scan-results/**
          sonar.javascript.lcov.reportPaths=coverage/lcov.info
          sonar.coverage.exclusions=**/*.config.js,**/coverage/**
          sonar.dependencyCheck.htmlReportPath=$(System.DefaultWorkingDirectory)/dependency-scan-results/dependency-check-report.html
          sonar.language=js

    - name: Run linting
      run: npm run lint
    
    - name: Run tests
      run: npm test
  
    - name: Run backstop
      run: npm run backstop:ci
